name: pystock-data-features
channels:
  - defaults
dependencies:
  - python=3.8
  - numpy
  - scipy
  - pandas
  - cloudpickle
  - pip:
    - git+https://github.com/mlflow/mlflow.git
    - sklearn
    - pandas_datareader==0.10.0
    - great-expectations==0.13.15
    - pandas-profiling==3.3.0
    - jinja2==3.0.3
    - xgboost
