name: pystock-data-features
channels:
  - defaults
dependencies:
  - python=3.8.5
  - numpy
  - scipy
  - pandas
  - cloudpickle
  - pip:
    - mlflow
    - sklearn
    - pandas_datareader
    - great-expectations==0.13.15
    - pandas-profiling
    - xgboost
