name: pystock-data-features
channels:
  - defaults
dependencies:
  - python=3.8.5
  - numpy=1.20.1
  - scipy
  - pandas
  - cloudpickle
  - pip:
    - git+git://github.com/mlflow/mlflow
    - sklearn
    - pandas_datareader
    - great-expectations==0.13.15
    - pandas-profiling
    - xgboost
